### ISSUE TITLE
Size of canvas

### ISSUE THREAD

**Issue by henrygodev** [DevRaeph/laravel-pdf-protect#3]
Hello, your package is very good, but I have a question. The canvas size in my files is "letter," but the output is adjusting to the "A4" format. How can I adjust or respect the original canvas size?

**Comment by DevRaeph** [comment]
Hey there, thank you for the information, i'll check this out and add more options.
I'll come back to you soon :)

**Comment by DevRaeph** [comment]
@HenryGarcia96 maybe send me a demo file which I can use for testing? :)

**Comment by henrygodev** [comment]
I send the example file.

[F-23091501000124.pdf](https://github.com/DevRaeph/laravel-pdf-protect/files/12623080/F-23091501000124.pdf)

**Comment by DevRaeph** [comment]
Hey @HenryGarcia96,
i've updated the whole package to a new version 2.0.0.
Now it supports different document sizes automatically and also Laravel 10 and PHP 8.2.
Please check out the README, the overall syntax and usages has changed.
The old function encrypt is still working and update, but also marked as deprecated after version 2.0.0.
