### ISSUE TITLE
Orientation Changes After Applying Password Protection with PDFPasswordProtect

### ISSUE THREAD

**Issue by lequangminh** [DevRaeph/laravel-pdf-protect#4]
When using the following code to apply password protection to a PDF file:

```
PDFPasswordProtect::setInputFile($input)
    ->setOutputFile($output)
    ->setPassword($password)
    ->secure();
```

The orientation of the PDF file changes from landscape to portrait, which differs from the original input file.

Expected Behavior:
The orientation of the PDF file should remain the same (landscape in this case) after applying the password protection.

Actual Behavior:
The orientation changes unexpectedly from landscape to portrait after applying the password protection.

Environment:
Laravel Version: 10
Package Version: 3.1
PHP Version: 8.1
Operating System: Linux

**Comment by lequangminh** [comment]
I have set the format to 'A4' using format('A4') and it worked as expected.

**Comment by DevRaeph** [comment]
Perfect! Thank you for your issue. 
I'll investigate this further, and maybe it's possible for me to set this programmatically.
